# Generated by Django 6.0.3 on 2026-04-26 21:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('team_or_members', models.CharField(max_length=200)),
                ('meeting_date', models.DateField()),
                ('meeting_time', models.TimeField()),
                ('platform', models.CharField(choices=[('Teams', 'Teams'), ('Zoom', 'Zoom'), ('Google Meet', 'Google Meet'), ('In Person', 'In Person')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
