# Generated by Django 6.0.3 on 2026-04-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_remove_healthcheckvote_card_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('draft', 'Draft')], default='sent', max_length=10),
        ),
    ]
