# Generated by Django 6.0.3 on 2026-04-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0006_healthcard_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcard',
            name='description',
            field=models.TextField(default='Default description'),
            preserve_default=False,
        ),
    ]
