# Generated by Django 6.0.3 on 2026-04-24 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0007_healthcard_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='card',
        ),
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='session',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='team',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='user',
        ),
        migrations.DeleteModel(
            name='HealthCard',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
