# Generated by Django 6.0.3 on 2026-04-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0011_remove_message_is_draft_alter_message_receiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
